# **Programación Básica con Python**

# **I. Conceptos básicos de programación**

Los conceptos básicos de programación son los fundamentos esenciales que permiten entender y escribir código en cualquier lenguaje de programación. Estos conceptos son la base para desarrollar software y resolver problemas mediante la creación de instrucciones que una computadora puede ejecutar. A continuación, se definen y describen los principales conceptos básicos de programación:

## 1.1. Tipos de datos

- **Definición**: Los tipos de datos especifican qué tipo de valor puede almacenar una variable, como números enteros, decimales, cadenas de texto o valores booleanos (verdadero/falso).

- **Descripción**: Los tipos de datos determinan las operaciones que se pueden realizar con una variable. Por ejemplo, no puedes sumar directamente un número y una palabra.

- **Ejemplo**:
- Entero (`int`): `42`
- Flotante (`float`): `3.14`
- Cadena (`string`): `"Hola"`
- Booleano (`bool`): `True` o `False`
- Especial (`NoneType`): `None`



In [1]:
dato_int = 25
dato_float= 20.000001

print(type(dato_int))
print(dato_int)

<class 'int'>
25


In [2]:
dato_str1 = "hola"
dato_str2 = "mundo"
dato_str3 = "2024"

print(type(dato_str1))
print(dato_str1)

<class 'str'>
hola


In [3]:
dato_bool1 = True
dato_bool2 = False

print(type(dato_bool1))
print(dato_bool1)


<class 'bool'>
True


En Python, `None` es un tipo de dato especial que representa la ausencia de un valor o un valor nulo. No es lo mismo que 0, una cadena vacía (`""`), o `False`.

# Nueva sección

In [4]:
data_none= None

print(data_none)
print(type(data_none))

None
<class 'NoneType'>


## 1.2. Variables

- **Definición**: Una variable es un espacio en la memoria de la computadora que almacena un valor, el cual puede cambiar durante la ejecución de un programa.

- **Descripción**: Las variables tienen un nombre y un tipo de dato (como números, texto o booleanos). Actúan como contenedores para guardar información que el programa usará o modificará.

- **Ejemplo**: En Python, `edad = 25` define una variable llamada `edad` con el valor 25.

In [5]:
# Datos y variables numericas
#-----------------------------


## 1.2. Operadores matemáticos

In [6]:
# suma
suma = dato_int + dato_float

# exponencial
exponente = 5**2

# division
cociente = 9/5
cociente_entero = 9//5
residuo = 9%5

print("suma =",suma)
print(type(suma))
print("exponente = ",exponente)
print("cociente =", cociente)
print("cociente_entero =", cociente_entero)
print("residuo =",residuo)

suma = 45.000001
<class 'float'>
exponente =  25
cociente = 1.8
cociente_entero = 1
residuo = 4


## 1.3. Importar paquetes o librerías en Python

En Python, un paquete o librería (los términos a menudo se usan indistintamente, aunque "paquete" tiene una estructura más específica) es una colección organizada de módulos.

```
paquete:
        aplicacion_01
        aplicacion_02
        . . . . . . .
        aplicacion_n
```

Formas de importar un paquete y sus aplicaciones

**Primera forma**
```
import paquete as pp

var = paquete.aplicacion_01(arg)
```

**Segunda forma**
```
import paquete as pp

var = pp.aplicacion_01(arg)
```

**Tercera forma**
```
from paquete import (aplicacion_01, aplicacion_04)

var_01 = aplicacion_01(arg)
var_02 = aplicacion_04(arg)
```

In [7]:
import math
import numpy as np

pi_math = math.pi
pi_np = np.pi
print(pi)
print(pi_np)

n_euler_math = math.e
n_euler_np = np.e
print(n_euler_math)
print(n_euler_np)

NameError: name 'pi' is not defined

## 1.4. Funciones algebraicas

**Exponencial**

$ y = b^{a}$

In [ ]:
y1 = n_euler**n_euler
print(y1)

**Valor absoluto**

si: $a<0, y = |a| = (-1) \times a$

si: $a>0, y = |a| = a$

In [ ]:
# funcion valor absoluto
y2 = np.abs(-1*num_int)
print(y2)

**Raíz cuadrada**

$y = \sqrt{b} = b^{\frac{1}{2}}$

In [ ]:
#funcion raiz cuadrada
y3 = np.sqrt(num_int)
print(y3)

**Raiz general**

$\sqrt[n]{b^m}= b\frac{m}{n}$

In [ ]:
y4 = 125**(1/3)
print(y4)

**Logaritmo**

$y = log_{b}x $

$x = b^y$

In [ ]:
# funcion logaritmo de 10 en base 10
y5 = np.log10(10)
print(y5)

# funcion logaritmo de 2 en base 2
y6 = np.log2(2)
print(y6)

# funcion logaritmo de e en base e
y7 = np.log(n_euler)
print(y7)

1.0
1.0
1.0


## 1.5. Operadores de comparación

In [ ]:
# operadores relacionales
# comparacion (==)
comp01 = num_int == num_float

# diferente (!=)
comp02 = num_int != num_float

# mayor que  (>)
comp03 = num_int > num_float

# menor que  (<)
comp04 = num_int < num_float

# mayor o igual que  (>=)
comp05 = num_int >= num_float

# menor o igual que  (<=)
comp06 = num_int <= num_float

print(type(comp01), comp01)
print(type(comp02), comp02)
print(type(comp03), comp03)
print(type(comp04), comp04)
print(type(comp05), comp05)
print(type(comp06), comp06)

<class 'bool'> False
<class 'bool'> True
<class 'bool'> True
<class 'bool'> False
<class 'bool'> True
<class 'bool'> False


## 1.6. Estrucuturas de Control I: `if`, `else` y `elif`

- **Definición**: Son instrucciones que controlan el flujo de ejecución de un programa, permitiendo tomar decisiones o repetir acciones.

- **Descripción**: Se dividen en:
  - **Condicionales**: Permiten ejecutar código solo si se cumple una condición (por ejemplo, `if`, `else`).


In [ ]:
# condicionales: if, elif, else
var = 23

if type(var)==int:
  print("var es valor entero")
  print("segunda accion de if")
else:
  print("var no es un numero entero")

var es valor entero
segunda accion de if


In [ ]:
# condicionales: if, elif, else
a = 7
b = 7

if a > b:
    print("(1)", a,">",b ,a > b)

elif a < b:
    print("(2)", a,"<",b ,a < b)

elif a == b:
    print("(3)", a,"==",b ,a == b)

(3) 7 == 7 True


## 1.7. Funciones: Parte I

In [ ]:
def area_cuadrado(lado):
  area = lado**2
  return area

In [ ]:
ac1 = area_cuadrado(4)
print(ac1)

16


In [ ]:
def convert_temp(data, tipo):
  if tipo=="K":
    temp = data + 273.15
    print(temp)
  elif tipo=="F":
    temp = (data) * 9/5 + 32
    print(temp)

In [ ]:
convert_temp(100, "F")
convert_temp(10, "F")
convert_temp(100, "K")

212.0
50.0
373.15


# **II. Estructura de datos**

## 2.1. Cadenas

In [ ]:
# Estructuras tipo cadena de caracteres
var_cadena = "las estaciones del año son: verano, otoño, invierno y primavera"

print(var_cadena)
print(len(var_cadena))

print(var_cadena[3:14])
print(type(var_cadena))

las estaciones del año son: verano, otoño, invierno y primavera
63
 estaciones
<class 'str'>


In [ ]:
departamentos_peru = "algunos departamentos de Perú son: Lima, Ica, Arequipa y Tacna"

print(departamentos_peru)
print(len(departamentos_peru))
print(departamentos_peru[35:39])
print(type(departamentos_peru))


algunos departamentos de Perú son: Lima, Ica, Arequipa y Tacna
62
Lima
<class 'str'>


In [ ]:
separar_frase = departamentos_peru.split()

print(separar_frase)
print(type(separar_frase))

['algunos', 'departamentos', 'de', 'Perú', 'son:', 'Lima,', 'Ica,', 'Arequipa', 'y', 'Tacna']
<class 'list'>


## 2.2. Listas

In [ ]:
# listas
var_lista01 = ["hola", 2024, "mundo", 2024.5]

print(var_lista01)
print(len(var_lista01))
print(var_lista01[0])

var_lista01[3]= "Peru 2025"
print(var_lista01)

print(type(var_lista01[1]))

['hola', 2024, 'mundo', 2024.5]
4
hola
['hola', 2024, 'mundo', 'Peru 2025']
<class 'int'>


In [ ]:
lista_02 = [12,3,3,2]

lista_03 = [1,2,3,4]

In [ ]:
suma_lista23 = lista_02 + lista_03
print(suma_lista23)

[12, 3, 3, 2, 1, 2, 3, 4]


In [ ]:
prod_lista23 = 3* lista_03
print(prod_lista23)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


## 2.3. Array 1D

In [ ]:
import numpy as np

# array 1D: np.array()
array_meses_num = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(array_meses_num)
print(type(array_meses_num))
print(len(array_meses_num))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>
12


In [ ]:
# array 1D: np.arange(val_i, num_vals, incremento)
array_arange01 = np.arange(-20, 10, 0.5)

print(array_arange01)
print(len(array_arange01))

[-20.  -19.5 -19.  -18.5 -18.  -17.5 -17.  -16.5 -16.  -15.5 -15.  -14.5
 -14.  -13.5 -13.  -12.5 -12.  -11.5 -11.  -10.5 -10.   -9.5  -9.   -8.5
  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5  -4.   -3.5  -3.   -2.5
  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5   2.    2.5   3.    3.5
   4.    4.5   5.    5.5   6.    6.5   7.    7.5   8.    8.5   9.    9.5]
60


In [ ]:
# array 1D: np.zeros()
array_zeros01 = np.zeros(4)

print(array_zeros01)
print(type(array_zeros01))
print(len(array_zeros01))
print(np.ndim(array_zeros01))
print(np.shape(array_zeros01))

print(var_lista01[1])
array_zeros01[2]= var_lista01[1]
print(array_zeros01)

[0. 0. 0. 0.]
<class 'numpy.ndarray'>
4
1
(4,)
2024
[   0.    0. 2024.    0.]


Operaciones con arrays.

In [ ]:
prod_escalar = 2*array_meses_num
print(prod_escalar)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [ ]:
array_linespace = np.linspace(1,10,12)
print(array_linespace)

[ 1.          1.81818182  2.63636364  3.45454545  4.27272727  5.09090909
  5.90909091  6.72727273  7.54545455  8.36363636  9.18181818 10.        ]


## 2.4. Data Frame

In [ ]:
# data frame
import pandas as pd

# crear data frame
df = pd.DataFrame()

print(df)

Empty DataFrame
Columns: []
Index: []


In [ ]:
temp_aire = 18*(1 + np.sin(2 * np.pi * data))
print(temp_aire)

[18.         28.58013454 35.11901729 35.11901729 28.58013454 18.
  7.41986546  0.88098271  0.88098271  7.41986546 18.         28.58013454
 35.11901729 35.11901729 28.58013454 18.          7.41986546  0.88098271
  0.88098271  7.41986546]


In [ ]:
fechas = pd.date_range(start=pd.to_datetime('today'), periods=len(temp_aire), freq='D')
#fechas = pd.date_range(start=pd.to_datetime('today'), periods=len(temp_aire), freq='D').sttftime('%Y-%m-%d')
print(fechas)

DatetimeIndex(['2025-08-08 21:39:42.582551', '2025-08-09 21:39:42.582551',
               '2025-08-10 21:39:42.582551', '2025-08-11 21:39:42.582551',
               '2025-08-12 21:39:42.582551', '2025-08-13 21:39:42.582551',
               '2025-08-14 21:39:42.582551', '2025-08-15 21:39:42.582551',
               '2025-08-16 21:39:42.582551', '2025-08-17 21:39:42.582551',
               '2025-08-18 21:39:42.582551', '2025-08-19 21:39:42.582551',
               '2025-08-20 21:39:42.582551', '2025-08-21 21:39:42.582551',
               '2025-08-22 21:39:42.582551', '2025-08-23 21:39:42.582551',
               '2025-08-24 21:39:42.582551', '2025-08-25 21:39:42.582551',
               '2025-08-26 21:39:42.582551', '2025-08-27 21:39:42.582551'],
              dtype='datetime64[ns]', freq='D')


In [ ]:
df["temperatura"]= temp_aire
print(df)

    temperatura                      fecha
0     18.000000 2025-08-08 21:36:59.977562
1     28.580135 2025-08-09 21:36:59.977562
2     35.119017 2025-08-10 21:36:59.977562
3     35.119017 2025-08-11 21:36:59.977562
4     28.580135 2025-08-12 21:36:59.977562
5     18.000000 2025-08-13 21:36:59.977562
6      7.419865 2025-08-14 21:36:59.977562
7      0.880983 2025-08-15 21:36:59.977562
8      0.880983 2025-08-16 21:36:59.977562
9      7.419865 2025-08-17 21:36:59.977562
10    18.000000 2025-08-18 21:36:59.977562
11    28.580135 2025-08-19 21:36:59.977562
12    35.119017 2025-08-20 21:36:59.977562
13    35.119017 2025-08-21 21:36:59.977562
14    28.580135 2025-08-22 21:36:59.977562
15    18.000000 2025-08-23 21:36:59.977562
16     7.419865 2025-08-24 21:36:59.977562
17     0.880983 2025-08-25 21:36:59.977562
18     0.880983 2025-08-26 21:36:59.977562
19     7.419865 2025-08-27 21:36:59.977562


In [ ]:
df["fecha"]= fechas
print(df)

    temperatura                      fecha
0     18.000000 2025-08-08 21:39:42.582551
1     28.580135 2025-08-09 21:39:42.582551
2     35.119017 2025-08-10 21:39:42.582551
3     35.119017 2025-08-11 21:39:42.582551
4     28.580135 2025-08-12 21:39:42.582551
5     18.000000 2025-08-13 21:39:42.582551
6      7.419865 2025-08-14 21:39:42.582551
7      0.880983 2025-08-15 21:39:42.582551
8      0.880983 2025-08-16 21:39:42.582551
9      7.419865 2025-08-17 21:39:42.582551
10    18.000000 2025-08-18 21:39:42.582551
11    28.580135 2025-08-19 21:39:42.582551
12    35.119017 2025-08-20 21:39:42.582551
13    35.119017 2025-08-21 21:39:42.582551
14    28.580135 2025-08-22 21:39:42.582551
15    18.000000 2025-08-23 21:39:42.582551
16     7.419865 2025-08-24 21:39:42.582551
17     0.880983 2025-08-25 21:39:42.582551
18     0.880983 2025-08-26 21:39:42.582551
19     7.419865 2025-08-27 21:39:42.582551


In [ ]:
hr = 2.5*temp_aire +5.6

df["humedad_relativa"] = hr
print(df)

    temperatura  datos_decimales  humedad_relativa
0     18.000000              0.0         50.600000
1     28.580135              0.1         77.050336
2     35.119017              0.2         93.397543
3     35.119017              0.3         93.397543
4     28.580135              0.4         77.050336
5     18.000000              0.5         50.600000
6      7.419865              0.6         24.149664
7      0.880983              0.7          7.802457
8      0.880983              0.8          7.802457
9      7.419865              0.9         24.149664
10    18.000000              1.0         50.600000
11    28.580135              1.1         77.050336
12    35.119017              1.2         93.397543
13    35.119017              1.3         93.397543
14    28.580135              1.4         77.050336
15    18.000000              1.5         50.600000
16     7.419865              1.6         24.149664
17     0.880983              1.7          7.802457
18     0.880983              1.

In [ ]:
# numero total de elementos o medidas del data frame
print(df.size)

# dimensiones del data frame
print(df.shape)

# nombres de las columnas
print(df.columns)

40
(20, 2)
Index(['temperatura', 'fecha'], dtype='object')


## 2.5. Estrucuturas de Control II: `for`, y `while`

- **Descripción**: Se dividen en:
  - **Bucles**: Repiten un bloque de código mientras una condición sea verdadera (por ejemplo, `for`, `while`).



```
var_lista01 = ["hola", 2024, "mundo", 2024.5]
                  0      1      2       3
```



In [ ]:
var_lista01[0] = "Hello!"

In [ ]:
print(var_lista01[0])
print(var_lista01[1])

Hello!
2024


Control de flujo: **for**


```
for arg01 in arg02:
  aplicacion_01
  aplicacion_02
    ........
  aplicacion_n
```



>Control de flujo **for** sobre  **listas**

In [ ]:
n_elem = len(var_lista01)
print(n_elem)

4


In [ ]:
for i in range(n_elem):
  print(var_lista01[i])

Hello!
2024
mundo
Peru 2025


>Control de flujo **for** a  **data frame**

## 2.6. Funciones: Parte II

# **III. Referencias**

**Libros y manuales**

- Libro de estadisitica con python

  https://www.editorial-sciela.org/index.php/sciela/article/view/16/49

- Introducción a la teoria de probabilidades

  https://ciladi.org/wp-content/uploads/Version_final_Introduccion-Probabilidad-Python-vf_Bayas-3.pdf

- Guía practica de análsis exploratorio de python

  https://datos.gob.es/sites/default/files/doc/file/guia_eda_python.pdf


**Cursos en linea**

- Estadística W3School:

  https://www.w3schools.com/statistics/index.php

- Estadística con python:

  https://docs.python.org/es/3/library/statistics.html

- Kaggle:

  https://www.kaggle.com/code/saurav9786/statistics-for-data-scientists

**Aplicaciones IA**

- Gemini iA

  https://gemini.google.com

- DeepSeek

  https://www.deepseek.com/

- Chat GPT

  https://chatgpt.com/

- Claude IA

  https://claude.ai/

- Julius IA:

  https://julius.ai



### Tipo de dato `None` en Python

En Python, `None` es un tipo de dato especial que representa la ausencia de un valor o un valor nulo. No es lo mismo que 0, una cadena vacía (`""`), o `False`.

**Características principales:**

*   **Representa la ausencia de valor:** Se utiliza comúnmente para indicar que una variable no tiene asignado un valor significativo, o que una función no devuelve explícitamente ningún valor (en cuyo caso, implícitamente devuelve `None`).
*   **Es un objeto singleton:** Solo hay una instancia de `None` en el sistema. Esto significa que si tienes varias variables a las que se les asigna `None`, todas apuntan al mismo objeto en memoria. Puedes comprobar esto usando el operador `is`.
*   **Su tipo es `NoneType`:** El tipo de `None` es `NoneType`.
*   **Es falsy en contextos booleanos:** Aunque no es `False`, `None` se evalúa como falso en contextos booleanos (por ejemplo, en una sentencia `if`).

**Usos comunes:**

*   **Inicialización de variables:** Para inicializar una variable cuando aún no se le ha asignado un valor real.
*   **Valor de retorno de funciones:** Las funciones que no tienen una sentencia `return` explícitamente (o que tienen `return` sin un valor) devuelven `None`.
*   **Indicador de valor opcional o faltante:** En la firma de funciones, para indicar que un argumento es opcional y que, si no se proporciona, tendrá un valor nulo.
*   **Comparación:** Para comprobar si una variable o el resultado de una operación es nulo utilizando el operador `is` (`mi_variable is None`). Es preferible usar `is None` en lugar de `== None` debido a la naturaleza singleton de `None`.

In [ ]:
print(type(None))

var_none = None

if var_none is None:
  print("La variable var_none es None")

if not var_none:
  print("La variable var_none es evaluada como False en un contexto booleano")