# **Programación Básica con Python**

# **I. Conceptos básicos de programación**

## 1.1. Tipos de datos y variables

Tipos fundamentales de datos definidos en Python.

In [1]:
# data caracter
#----------------------
var_1 = "hola"
var_2 = 2025
var_3 = "15"
var_4 = None
var_5 = True
va_6 = False

print("esto es el contenido de la variable var_1 = ",var_1, ", que es tipo no numerico")
print(type(var_1))
print(type(var_2))
print(type(var_3))

esto es el contenido de la variable var_1 =  hola , que es tipo no numerico
<class 'str'>
<class 'int'>
<class 'str'>


In [2]:
# Datos y variables numericas
#-----------------------------
num_int = 25
num_float= 20.000001

print(type(num_int), type(num_float))

<class 'int'> <class 'float'>


## 1.2. Operadores matemáticos

In [3]:
# suma
suma = num_int + num_float

# exponencial
exponente = 5**2

# division
cociente = 9/5
cociente_entero = 9//5
residuo = 9%5

print("suma =",suma)
print(type(suma))
print("exponente = ",exponente)
print("cociente =", cociente)
print("cociente_entero =", cociente_entero)
print("residuo =",residuo)

suma = 45.000001
<class 'float'>
exponente =  25
cociente = 1.8
cociente_entero = 1
residuo = 4


## 1.3. Importar paquetes o librerías en Python

En Python, un paquete o librería (los términos a menudo se usan indistintamente, aunque "paquete" tiene una estructura más específica) es una colección organizada de módulos.

```
paquete:
        aplicacion_01
        aplicacion_02
        . . . . . . .
        aplicacion_n
```

Formas de importar un paquete y sus aplicaciones

**Primera forma**
```
import paquete as pp

var = paquete.aplicacion_01(arg)
```

**Segunda forma**
```
import paquete as pp

var = pp.aplicacion_01(arg)
```

**Tercera forma**
```
from paquete import (aplicacion_01, aplicacion_04)

var_01 = aplicacion_01(arg)
var_02 = aplicacion_04(arg)
```

In [4]:
import math
import numpy as np

pi_math = math.pi
pi_np = np.pi
print(pi_math)
print(pi_np)
n_euler_math = math.e
n_euler_np = np.e
print(n_euler_math)
print(n_euler_np)

3.141592653589793
3.141592653589793
2.718281828459045
2.718281828459045


## 1.4. Funciones algebraicas

**Exponencial**

$ y = b^{a}$

In [5]:
y1 = n_euler_math**n_euler_math
print(y1)

15.154262241479259


**Valor absoluto**

si: $a<0, y = |a| = (-1) \times a$

si: $a>0, y = |a| = a$

In [6]:
# funcion valor absoluto
y2 = np.abs(-1*num_int)
print(y2)

25


**Raíz cuadrada**

$y = \sqrt{b} = b^{\frac{1}{2}}$

In [7]:
#funcion raiz cuadrada
y3 = np.sqrt(num_int)
print(y3)

5.0


**Raiz general**

$\sqrt[n]{b^m}= b\frac{m}{n}$

In [8]:
y4 = 125**(1/3)
print(y4)

4.999999999999999


**Logaritmo**

$y = log_{b}x $

$x = b^y$

In [9]:
# funcion logaritmo de 10 en base 10
y5 = np.log10(10)
print(y5)

# funcion logaritmo de 2 en base 2
y6 = np.log2(2)
print(y6)

# funcion logaritmo de e en base e
y7 = np.log(n_euler_math)
print(y7)

1.0
1.0
1.0


## 1.5. Operadores de comparación

In [10]:
# operadores relacionales
# comparacion (==)
comp01 = num_int == num_float

# diferente (!=)
comp02 = num_int != num_float

# mayor que  (>)
comp03 = num_int > num_float

# menor que  (<)
comp04 = num_int < num_float

# mayor o igual que  (>=)
comp05 = num_int >= num_float

# menor o igual que  (<=)
comp06 = num_int <= num_float

print(type(comp01), comp01)
print(type(comp02), comp02)
print(type(comp03), comp03)
print(type(comp04), comp04)
print(type(comp05), comp05)
print(type(comp06), comp06)

<class 'bool'> False
<class 'bool'> True
<class 'bool'> True
<class 'bool'> False
<class 'bool'> True
<class 'bool'> False


## 1.6. Condiciones

In [11]:
# condicionales: if, elif, else
var = 23

if type(var)==int:
  print("var es valor entero")
  print("segunda accion de if")
else:
  print("var no es un numero entero")

var es valor entero
segunda accion de if


In [12]:
# condicionales: if, elif, else
a = 7
b = 7

if a > b:
    print("(1)", a,">",b ,a > b)

elif a < b:
    print("(2)", a,"<",b ,a < b)

elif a == b:
    print("(3)", a,"==",b ,a == b)

(3) 7 == 7 True


## 1.7. Funciones: Parte I

In [13]:
def area_cuadrado(lado):
  area = lado**2
  return area

In [14]:
ac1 = area_cuadrado(4)
print(ac1)

16


In [15]:
def convert_temp(data, tipo):
  if tipo=="K":
    temp = data + 273.15
    print(temp)
  elif tipo=="F":
    temp = (data) * 9/5 + 32
    print(temp)

In [16]:
convert_temp(100, "F")
convert_temp(10, "F")
convert_temp(100, "K")

212.0
50.0
373.15


# **II. Estructura de datos**

## 2.1. Cadenas

In [17]:
# Estructuras tipo cadena de caracteres
var_cadena = "las estaciones del año son: verano, otoño, invierno y primavera"

print(var_cadena)
print(len(var_cadena))

print(var_cadena[3:14])
print(type(var_cadena))

las estaciones del año son: verano, otoño, invierno y primavera
63
 estaciones
<class 'str'>


In [18]:
departamentos_peru = "algunos departamentos de Perú son: Lima, Ica, Arequipa y Tacna"

print(departamentos_peru)
print(len(departamentos_peru))
print(departamentos_peru[35:39])
print(type(departamentos_peru))


algunos departamentos de Perú son: Lima, Ica, Arequipa y Tacna
62
Lima
<class 'str'>


In [19]:
separar_frase = departamentos_peru.split()

print(separar_frase)
print(type(separar_frase))

['algunos', 'departamentos', 'de', 'Perú', 'son:', 'Lima,', 'Ica,', 'Arequipa', 'y', 'Tacna']
<class 'list'>


## 2.2. Listas

In [20]:
# listas
var_lista01 = ["hola", 2024, "mundo", 2024.5]

print(var_lista01)
print(len(var_lista01))
print(var_lista01[0])

var_lista01[3]= "Peru 2025"
print(var_lista01)

print(type(var_lista01[1]))

['hola', 2024, 'mundo', 2024.5]
4
hola
['hola', 2024, 'mundo', 'Peru 2025']
<class 'int'>


In [21]:
lista_02 = [12,3,3,2]

lista_03 = [1,2,3,4]

In [22]:
suma_lista23 = lista_02 + lista_03
print(suma_lista23)

[12, 3, 3, 2, 1, 2, 3, 4]


In [23]:
prod_lista23 = 3* lista_03
print(prod_lista23)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


## 2.3. Array 1D

In [24]:
import numpy as np

# array 1D: np.array()
array_meses_num = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(array_meses_num)
print(type(array_meses_num))
print(len(array_meses_num))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>
12


In [25]:
# array 1D: np.arange(val_i, num_vals, incremento)
array_arange01 = np.arange(-20, 10, 0.5)

print(array_arange01)
print(len(array_arange01))

[-20.  -19.5 -19.  -18.5 -18.  -17.5 -17.  -16.5 -16.  -15.5 -15.  -14.5
 -14.  -13.5 -13.  -12.5 -12.  -11.5 -11.  -10.5 -10.   -9.5  -9.   -8.5
  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5  -4.   -3.5  -3.   -2.5
  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5   2.    2.5   3.    3.5
   4.    4.5   5.    5.5   6.    6.5   7.    7.5   8.    8.5   9.    9.5]
60


In [26]:
# array 1D: np.zeros()
array_zeros01 = np.zeros(4)

print(array_zeros01)
print(type(array_zeros01))
print(len(array_zeros01))
print(np.ndim(array_zeros01))
print(np.shape(array_zeros01))

print(var_lista01[1])
array_zeros01[2]= var_lista01[1]
print(array_zeros01)

[0. 0. 0. 0.]
<class 'numpy.ndarray'>
4
1
(4,)
2024
[   0.    0. 2024.    0.]


Operaciones con arrays.

In [27]:
prod_escalar = 2*array_meses_num
print(prod_escalar)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [28]:
array_linespace = np.linspace(1,10,12)
print(array_linespace)

[ 1.          1.81818182  2.63636364  3.45454545  4.27272727  5.09090909
  5.90909091  6.72727273  7.54545455  8.36363636  9.18181818 10.        ]


## 2.4. Data Frame

In [29]:
# data frame
import pandas as pd

# crear data frame
df = pd.DataFrame()

print(df)

Empty DataFrame
Columns: []
Index: []


In [30]:
data = np.linspace(0, 2, 20)
temp_aire = 18*(1 + np.sin(2 * np.pi * data))
print(temp_aire)

[18.         29.05582883 35.44920479 34.48391988 26.56705307 15.03729737
  4.75696961  0.06147913  2.93100339 12.15540955 23.84459045 33.06899661
 35.93852087 31.24303039 20.96270263  9.43294693  1.51608012  0.55079521
  6.94417117 18.        ]


In [31]:
fechas = pd.date_range(start=pd.to_datetime('today'), periods=len(temp_aire), freq='D')
#fechas = pd.date_range(start=pd.to_datetime('today'), periods=len(temp_aire), freq='D').sttftime('%Y-%m-%d')
print(fechas)

DatetimeIndex(['2025-08-28 14:49:55.876758', '2025-08-29 14:49:55.876758',
               '2025-08-30 14:49:55.876758', '2025-08-31 14:49:55.876758',
               '2025-09-01 14:49:55.876758', '2025-09-02 14:49:55.876758',
               '2025-09-03 14:49:55.876758', '2025-09-04 14:49:55.876758',
               '2025-09-05 14:49:55.876758', '2025-09-06 14:49:55.876758',
               '2025-09-07 14:49:55.876758', '2025-09-08 14:49:55.876758',
               '2025-09-09 14:49:55.876758', '2025-09-10 14:49:55.876758',
               '2025-09-11 14:49:55.876758', '2025-09-12 14:49:55.876758',
               '2025-09-13 14:49:55.876758', '2025-09-14 14:49:55.876758',
               '2025-09-15 14:49:55.876758', '2025-09-16 14:49:55.876758'],
              dtype='datetime64[ns]', freq='D')


In [32]:
df["temperatura"]= temp_aire
print(df)

    temperatura
0     18.000000
1     29.055829
2     35.449205
3     34.483920
4     26.567053
5     15.037297
6      4.756970
7      0.061479
8      2.931003
9     12.155410
10    23.844590
11    33.068997
12    35.938521
13    31.243030
14    20.962703
15     9.432947
16     1.516080
17     0.550795
18     6.944171
19    18.000000


In [33]:
df["fecha"]= fechas
print(df)

    temperatura                      fecha
0     18.000000 2025-08-28 14:49:55.876758
1     29.055829 2025-08-29 14:49:55.876758
2     35.449205 2025-08-30 14:49:55.876758
3     34.483920 2025-08-31 14:49:55.876758
4     26.567053 2025-09-01 14:49:55.876758
5     15.037297 2025-09-02 14:49:55.876758
6      4.756970 2025-09-03 14:49:55.876758
7      0.061479 2025-09-04 14:49:55.876758
8      2.931003 2025-09-05 14:49:55.876758
9     12.155410 2025-09-06 14:49:55.876758
10    23.844590 2025-09-07 14:49:55.876758
11    33.068997 2025-09-08 14:49:55.876758
12    35.938521 2025-09-09 14:49:55.876758
13    31.243030 2025-09-10 14:49:55.876758
14    20.962703 2025-09-11 14:49:55.876758
15     9.432947 2025-09-12 14:49:55.876758
16     1.516080 2025-09-13 14:49:55.876758
17     0.550795 2025-09-14 14:49:55.876758
18     6.944171 2025-09-15 14:49:55.876758
19    18.000000 2025-09-16 14:49:55.876758


In [34]:
hr = 2.5*temp_aire +5.6

df["humedad_relativa"] = hr
print(df)

    temperatura                      fecha  humedad_relativa
0     18.000000 2025-08-28 14:49:55.876758         50.600000
1     29.055829 2025-08-29 14:49:55.876758         78.239572
2     35.449205 2025-08-30 14:49:55.876758         94.223012
3     34.483920 2025-08-31 14:49:55.876758         91.809800
4     26.567053 2025-09-01 14:49:55.876758         72.017633
5     15.037297 2025-09-02 14:49:55.876758         43.193243
6      4.756970 2025-09-03 14:49:55.876758         17.492424
7      0.061479 2025-09-04 14:49:55.876758          5.753698
8      2.931003 2025-09-05 14:49:55.876758         12.927508
9     12.155410 2025-09-06 14:49:55.876758         35.988524
10    23.844590 2025-09-07 14:49:55.876758         65.211476
11    33.068997 2025-09-08 14:49:55.876758         88.272492
12    35.938521 2025-09-09 14:49:55.876758         95.446302
13    31.243030 2025-09-10 14:49:55.876758         83.707576
14    20.962703 2025-09-11 14:49:55.876758         58.006757
15     9.432947 2025-09-

In [35]:
# numero total de elementos o medidas del data frame
print(df.size)

# dimensiones del data frame
print(df.shape)

# nombres de las columnas
print(df.columns)

60
(20, 3)
Index(['temperatura', 'fecha', 'humedad_relativa'], dtype='object')


## 2.5. Control de flujo



```
var_lista01 = ["hola", 2024, "mundo", 2024.5]
                  0      1      2       3
```



In [36]:
var_lista01[0] = "Hello!"

In [37]:
print(var_lista01[0])
print(var_lista01[1])

Hello!
2024


Control de flujo: **for**


```
for arg01 in arg02:
  aplicacion_01
  aplicacion_02
    ........
  aplicacion_n
```



>Control de flujo **for** sobre  **listas**

In [38]:
n_elem = len(var_lista01)
print(n_elem)

4


In [39]:
for i in range(n_elem):
  print(var_lista01[i])

Hello!
2024
mundo
Peru 2025


>Control de flujo **for** a  **data frame**

## 2.6. Funciones: Parte II

# **III. Referencias**

**Libros y manuales**

- Libro de estadisitica con python

  https://www.editorial-sciela.org/index.php/sciela/article/view/16/49

- Introducción a la teoria de probabilidades

  https://ciladi.org/wp-content/uploads/Version_final_Introduccion-Probabilidad-Python-vf_Bayas-3.pdf

- Guía practica de análsis exploratorio de python

  https://datos.gob.es/sites/default/files/doc/file/guia_eda_python.pdf


**Cursos en linea**

- Estadística W3School:

  https://www.w3schools.com/statistics/index.php

- Estadística con python:

  https://docs.python.org/es/3/library/statistics.html

- Kaggle:

  https://www.kaggle.com/code/saurav9786/statistics-for-data-scientists

**Aplicaciones IA**

- Gemini iA

  https://gemini.google.com

- DeepSeek

  https://www.deepseek.com/

- Chat GPT

  https://chatgpt.com/

- Claude IA

  https://claude.ai/

- Julius IA:

  https://julius.ai

